name: diannemurphy

markdown: kramdown
exclude: [bower_components, Gemfile, Gemfile.lock, less, '*.json', '*.rb', Gruntfile.js, README.md, node_modules, '.mdastrc', '.htmlhintrc', '.scss-lint.yml' ]
highlighter: pygments
paginate: 5
permalink:     none

baseurl:
url:      http://localhost:4000

gems:
- jekyll-redirect-from
- jekyll-sitemap


collections:
  artwork:
    description: "Dianne's artwork"
    output: true

# Setting some defaults for collections - layouts, collection information.
# with more to follow

defaults:
 -
   scope:
     path: ""
     type: artwork
   values:
     layout: post
     info: Dianne
