# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:
  - jekyll-paginate
  - jekyll-sitemap

exclude: [bower_components, Gemfile,Gemfile.lock,Gruntfile.js,package.json,README.md,node_modules]

# Permalinks
permalink:        none
relative_permalinks: false

# Setup
title:            Dianne Murphy
tagline:          'Printmaker and Artist'
description:      'Dianne Murphy is a printmaker and artist based in Wales - producing a range of limited edition hand inked etchings'
url:              http://www.diannemurphy.co.uk
baseurl:

# About/contact
author:
  name:              Dianne Murphy
  url:               http://www.diannemurphy.co.uk
  email:             dianne@mearso.com
  saatchiart:        https://www.saatchiart.com/Murphy
  artfinder:         https://www.artfinder.com/dianne-murphy#/
# paginate: 5
# paginate_path: "/gallery/page:num/"


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
